"""
Recommendation models for license optimization.

Models representing optimization suggestions with ROI calculations,
risk assessment, and implementation tracking.
"""

from app.utils.time import utcnow
from datetime import datetime
from typing import Optional, List
from decimal import Decimal
from enum import Enum

from pydantic import BaseModel, Field, ConfigDict, computed_field, field_validator


class RecommendationType(str, Enum):
    """Types of recommendation actions (used by factory)."""
    DEACTIVATE = "DEACTIVATE"
    DOWNGRADE = "DOWNGRADE"
    KEEP = "KEEP"
    UPGRADE = "UPGRADE"
    OPTIMIZE = "OPTIMIZE"
    REVIEW = "REVIEW"


class RecommendationAction(str, Enum):
    """Types of recommendation actions."""
    DEACTIVATE = "deactivate"
    DOWNGRADE = "downgrade"
    KEEP = "keep"
    UPGRADE = "upgrade"


class Priority(str, Enum):
    """Priority levels for recommendations."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ImpactLevel(str, Enum):
    """Impact levels for recommendations."""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NONE = "NONE"


class RiskLevel(str, Enum):
    """Risk levels for implementing recommendations."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class RecommendationStatus(str, Enum):
    """Status of recommendation implementation."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    IMPLEMENTED = "implemented"


class Recommendation(BaseModel):
    """
    License optimization recommendation.
    
    Suggests specific actions to optimize license costs while
    maintaining user productivity and minimizing risks.
    """
    model_config = ConfigDict(
        frozen=False,
        validate_assignment=True,
    )

    # User identification
    user_id: str
    username: str
    email: Optional[str] = None
    license_type: str = Field(..., description="Current license type")
    
    # Recommendation
    type: RecommendationType = Field(..., description="Type of recommendation")
    title: str = Field(..., description="Short title of recommendation")
    description: str = Field(..., description="Detailed description")
    rationale: List[str] = Field(default_factory=list, description="Reasoning points")
    
    # Financial impact
    expected_savings: Decimal = Field(default=Decimal("0"), ge=0)
    monthly_savings: Decimal = Field(default=Decimal("0"))
    annual_savings: Decimal = Field(default=Decimal("0"))
    
    # Priority and impact
    priority: Priority = Field(default=Priority.LOW)
    impact: ImpactLevel = Field(default=ImpactLevel.NONE)
    
    # Risk assessment
    risk_level: str = Field(default="Low")
    implementation_complexity: str = Field(default="Easy")
    implementation_time_days: int = Field(default=1, ge=0)
    
    # Approval and workflows
    requires_manager_approval: bool = Field(default=False)
    affected_workflows: List[str] = Field(default_factory=list)
    
    # Recommended state (optional)
    recommended_license: Optional[str] = Field(None, description="Recommended license type")
    recommended_cost_monthly: Optional[Decimal] = Field(None, ge=0)
    
    # Metadata
    created_at: datetime = Field(default_factory=utcnow)
    status: RecommendationStatus = Field(default=RecommendationStatus.PENDING)
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0)
    
    @field_validator("monthly_savings", "annual_savings")
    @classmethod
    def validate_savings(cls, v: Decimal) -> Decimal:
        """Ensure savings can be negative for upgrades."""
        return v
    
    @computed_field
    @property
    def is_cost_reduction(self) -> bool:
        """Check if recommendation reduces costs."""
        return self.monthly_savings > 0
    
    @computed_field
    @property
    def is_high_impact(self) -> bool:
        """Check if recommendation has high financial impact (>$50/month)."""
        return abs(self.monthly_savings) >= 50


class PlanStep(BaseModel):
    """A single step in an ActionPlan (typically GPT-4-generated)."""

    model_config = ConfigDict(frozen=False)

    title: str
    description: str
    duration_days: int = Field(default=1, ge=0)
    resources: List[str] = Field(default_factory=list)
    success_criteria: List[str] = Field(default_factory=list)


class PlanRisk(BaseModel):
    model_config = ConfigDict(frozen=False)
    risk: str
    mitigation: str


class ActionPlan(BaseModel):
    """CFO-facing optimization plan, generated by ``PlanGenerator`` (GPT-4).

    Designed to be embedded directly in the PDF report and JSON API responses.
    """

    model_config = ConfigDict(frozen=False)

    title: str = "Plan d'optimisation des licences Salesforce"
    executive_summary: str = ""
    steps: List[PlanStep] = Field(default_factory=list)
    quick_wins: List[str] = Field(default_factory=list)
    risks: List[PlanRisk] = Field(default_factory=list)
    timeline: str = "30-90 jours"

    # Financial roll-up
    total_estimated_savings: Decimal = Field(default=Decimal("0"))
    annual_estimated_savings: Decimal = Field(default=Decimal("0"))

    # Metadata
    generated_at: datetime = Field(default_factory=utcnow)
    model_version: Optional[str] = Field(
        default=None, description="GPT model used to produce this plan"
    )

    @computed_field
    @property
    def step_count(self) -> int:
        return len(self.steps)

    @computed_field
    @property
    def high_priority_quick_wins(self) -> List[str]:
        return self.quick_wins[:5]

