"""Security Alert model for permission monitoring."""
from datetime import datetime
from uuid import uuid4
from typing import Optional

from sqlalchemy import String, DateTime, ForeignKey, func, Text, Enum as SQLEnum, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
import enum

from app.database import Base


class AlertType(enum.Enum):
    """Types of security alerts."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class AlertStatus(enum.Enum):
    """Status of security alert."""
    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"


class SecurityAlert(Base):
    """
    Security Alert model.
    
    Stores security alerts generated by permission monitoring.
    Tracks critical permissions and anomalies.
    """
    __tablename__ = "security_alerts"
    __table_args__ = (
        Index('idx_security_alert_tenant', 'tenant_id'),
        Index('idx_security_alert_type', 'alert_type'),
        Index('idx_security_alert_status', 'status'),
        Index('idx_security_alert_detected', 'detected_at'),
    )

    id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        index=True
    )
    tenant_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    # Alert details
    alert_type: Mapped[AlertType] = mapped_column(
        SQLEnum(AlertType),
        nullable=False
    )
    permission: Mapped[str] = mapped_column(String(100), nullable=False)
    user_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sf_users.id", ondelete="SET NULL"),
        nullable=True
    )
    
    # Description and action
    description: Mapped[str] = mapped_column(Text, nullable=False)
    recommended_action: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Status tracking
    status: Mapped[AlertStatus] = mapped_column(
        SQLEnum(AlertStatus),
        nullable=False,
        default=AlertStatus.OPEN
    )
    
    # Metadata
    detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )
    
    # Relationships
    tenant: Mapped["Tenant"] = relationship("Tenant", back_populates="security_alerts")

    def __repr__(self) -> str:
        return f"<SecurityAlert(id={self.id}, type={self.alert_type.value}, status={self.status.value})>"

